version: '3'
volumes:
  mongodb_volume:

services:
  trading:
    build: trading-service/
    restart: always
    ports:
      - 8080:8080


  mongodb:
    image: mongo:latest
    volumes:
    - mongodb_volume:/data/db
    restart: always


