version: "3.7"

services:
  trading:
    build: trading-service/
    container_name: trading
    networks:
      - auction
    restart: always
    environment:
      - TZ=Europe/Minsk
    ports:
    - "8080:8080"
    depends_on:
    - mongodb
    - payment
    - chat


  payment:
    build: payment-service/
    container_name: payment
    networks:
      - auction
    restart: always
    environment:
      - TZ=Europe/Minsk
    ports:
    - "8081:8080"
    depends_on:
    - mongodb


  chat:
    build: chat-service/
    container_name: chat
    networks:
      - auction
    restart: always
    environment:
      - TZ=Europe/Minsk
    ports:
    - "8082:8080"
    depends_on:
    - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - auction
    restart: always
    environment:
      - TZ=Europe/Minsk
    ports:
    - 27018:27017
    volumes:
      - ./db-data:/mongodb/data/db

networks:
  auction:
    driver: "bridge"