version: "3.7"

services:
  trading:
    build: trading-service/
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
    - 27017:27017


